name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release extension
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install zip

      - name: Get tag
        id: ghtag
        run: echo ::set-output name=tag::$(git describe --tags)

      - name: Create release file
        run: zip shell.zip shell.php -r

      - name: Create release
        env:
          GH_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.ghtag.outputs.tag }}
        run: |
          gh release create ${RELEASE_TAG} --title ${RELEASE_TAG} --generate-notes
          gh release upload ${RELEASE_TAG} shell.zip
